# Generated by Django 5.0.14 on 2026-08-05 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('spent_eur', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=7, unique=True)),
                ('spent_eur', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('external_id', models.CharField(max_length=200)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('is_public_figure', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('platform', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('platform', models.CharField(default='unknown', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('MAIN', 'Foro principal'), ('OFFTOPIC', 'Off-Topic')], default='MAIN', max_length=10)),
                ('status', models.CharField(choices=[('NEW', 'Nuevo'), ('CHEAP_RUNNING', 'Fase barata en curso'), ('PENDING_VALIDATION', 'Pendiente de validación (5 votos / 3 días)'), ('FULL_QUEUED', 'Análisis completo en cola'), ('FULL_RUNNING', 'Análisis completo en curso'), ('DONE', 'Analizado'), ('OFFTOPIC_SIGNALED', 'Off-Topic con señales'), ('OFFTOPIC_RAW', 'Off-Topic sin analizar (voluntario)'), ('HELD_FOR_REVIEW', 'Retenido (anti-acoso)'), ('FAILED', 'Error')], default='NEW', max_length=24)),
                ('voluntary_offtopic', models.BooleanField(default=False)),
                ('is_adult', models.BooleanField(default=False)),
                ('adult_flag_source', models.CharField(blank=True, default='', max_length=10)),
                ('manipulation_detected', models.BooleanField(default=False)),
                ('relegation_reason', models.CharField(blank=True, default='', max_length=200)),
                ('validation_deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_posts', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='analysis.channel')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('served_from_cache', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='analysis.post')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_seconds', models.FloatField()),
                ('end_seconds', models.FloatField()),
                ('text', models.TextField()),
                ('signal', models.CharField(blank=True, choices=[('', '—'), ('FACTUAL_UNVERIFIED', 'Afirmación factual (no verificada)'), ('OPINION', 'Opinión'), ('CONTRADICTS_MODEL', '⚠️ Contradice conocimiento general del modelo, sin verificar')], default='', max_length=24)),
                ('speaker_label', models.CharField(blank=True, default='', max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_segments', to='analysis.post')),
            ],
            options={
                'ordering': ['start_seconds'],
            },
        ),
        migrations.CreateModel(
            name='ValidationVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('VALIDATE', 'Es factual'), ('RESCUE', 'Rescatar de Off-Topic')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_votes', to='analysis.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'user', 'kind')},
            },
        ),
    ]
