# Generated by Django 5.0.14 on 2026-08-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('politica', 'Política'), ('salud', 'Salud'), ('ciencia', 'Ciencia'), ('economia', 'Economía'), ('sucesos', 'Sucesos'), ('internacional', 'Internacional'), ('tecnologia', 'Tecnología'), ('medioambiente', 'Medioambiente'), ('deporte', 'Deporte'), ('cultura', 'Cultura'), ('sociedad', 'Sociedad'), ('otros', 'Otros')], default='otros', max_length=16),
        ),
    ]
