# Generated by Django 5.0.14 on 2026-08-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_post_tags_post_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='opus_rescanned',
            field=models.BooleanField(default=False),
        ),
    ]
