# Generated by Django 5.0.14 on 2026-08-05 10:52

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_original', models.TextField()),
                ('language', models.CharField(default='es', max_length=8)),
                ('text_pivot_en', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=140, null=True, unique=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384, null=True)),
                ('color', models.CharField(choices=[('GREEN', '🟢 Verificado'), ('AMBER', '🟡 Engañoso o sin contexto'), ('RED', '🔴 Falso'), ('GREY', '⚪ No verificable')], default='GREY', max_length=6)),
                ('consolidated', models.BooleanField(default=False)),
                ('what_is_claimed', models.TextField(blank=True)),
                ('what_evidence_says', models.TextField(blank=True)),
                ('the_difference', models.TextField(blank=True)),
                ('sensitive', models.CharField(blank=True, default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interlocutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('is_public_figure', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='wiki.claim')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='analysis.transcriptsegment')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimSlugHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.SlugField(max_length=140, unique=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_slugs', to='wiki.claim')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('GREEN', '🟢 Verificado'), ('AMBER', '🟡 Engañoso o sin contexto'), ('RED', '🔴 Falso'), ('GREY', '⚪ No verificable')], max_length=6)),
                ('body_snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='wiki.claim')),
            ],
        ),
        migrations.CreateModel(
            name='InterlocutorSlugHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.SlugField(max_length=170, unique=True)),
                ('interlocutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_slugs', to='wiki.interlocutor')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('TRANSCRIPT', 'Transcripción errónea'), ('BROKEN_SOURCE', 'Fuente rota'), ('DISPUTED', 'Veredicto discutible'), ('CONTEXT', 'Falta contexto'), ('AUTHOR', 'Soy el autor')], max_length=14)),
                ('body', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='wiki.claim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=600)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='wiki.claim')),
            ],
        ),
        migrations.CreateModel(
            name='SpeakerNameProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_label', models.CharField(max_length=20)),
                ('candidate_name', models.CharField(max_length=160)),
                ('photo_url', models.URLField(blank=True, default='', max_length=400)),
                ('source', models.CharField(blank=True, default='', max_length=10)),
                ('confirmed', models.BooleanField(default=False)),
                ('interlocutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.interlocutor')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_proposals', to='analysis.post')),
            ],
            options={
                'unique_together': {('post', 'speaker_label', 'candidate_name')},
            },
        ),
        migrations.CreateModel(
            name='ClaimFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='wiki.claim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('claim', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SpeakerNameVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='wiki.speakernameproposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('proposal', 'user')},
            },
        ),
    ]
