# Generated by Django 5.0.14 on 2026-08-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_claim_sources_ok'),
    ]

    operations = [
        migrations.AddField(
            model_name='interlocutor',
            name='description',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='interlocutor',
            name='photo_url',
            field=models.URLField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='interlocutor',
            name='wikidata_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='speakernameproposal',
            name='description',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='speakernameproposal',
            name='wikidata_id',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
